export let menClothes=[
    {
        Name:"T-shirt",
    Price:"100",
    Image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_dBJaSfsFH-dw17KqI3FYyl01ZPgsy1ab2g&usqp=CAU",
    ProdId:100
    },
    {
        Name:"Shirt",
        Price:"200",
        Image:"https://images.bestsellerclothing.in/data/selected/oct-07-2021/203923802_5.jpg?width=1080&height=1355&mode=fill&fill=blur&format=auto",
        ProdId:101
    },
    {
        Name:"Jeans",
    Price:"300",
    Image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpPIVeY7h5sbqAZjsttg2f92-btJp9tXTPDw&usqp=CAU",
    ProdId:102
    },
    {
        Name:"Pant",
    Price:"400",
    Image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl5Qmxuq1ePe145AAluaAuZ9OofFG6bmKuSQ&usqp=CAU",
    ProdId:103
    },
    {
        Name:"Hoodie",
    Price:"500",
    Image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU",
    ProdId:104
    },
    {
        Name:"SweatShirt",
    Price:"600",
    Image:
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyKKRoAbfyCv8qGhn4HDWtodopPN54Kb8of3IGv4VGmuF6YvJPP5OmjnlofWkaRqep50M&usqp=CAU"    ,
    ProdId:104
    },
    {
        Name:"HankerCheif",
    Price:"600",
    Image:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU"
    ,
    ProdId:104
    },
    {
        Name:"Tie",
    Price:"800",
    Image:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU"
    ,
    ProdId:104
    },
    {
        Name:"Coat",
    Price:"900",
    Image:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU"
    ,
    ProdId:104
    },
    {
        Name:"Blazer",
    Price:"1000",
    Image:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU"
    ,
    ProdId:104
    },
    {
        Name:"Towel",
    Price:"1100",
    Image:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU"
    ,
    ProdId:104
    },
    {
        Name:"Socks",
    Price:"1200",
    Image:
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR341Dv1LBeksfbZweoxJPB-ZK2mdtLKAdiZA&usqp=CAU"
    ,
    ProdId:104
    }

];